name: Daily News Digest

on:
  schedule:
    - cron: '0 8 * * *'  # runs daily at 08:00 UTC
  workflow_dispatch:
jobs:
  send_digest:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      NEWS_API_KEY:    ${{ secrets.NEWS_API_KEY }}
      SERP_API_KEY:    ${{ secrets.SERP_API_KEY }}
      GEMINI_API_KEY:  ${{ secrets.GEMINI_API_KEY }}
      CHANNEL_ID:      ${{ secrets.CHANNEL_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run news bot
        run: python bot.py
